platform: linux | osx

analyzers:
 - cpplint: true
   include: ["*.cpp", "*.h", "*.hpp", "*.c"]
   path: 
   - ./src/base
   - ./src/ali_search
   filters:
   - -whitespace
   - +whitespace/braces
   style: google