analyzers:
 - cpplint: true
   filters: 
   - -whitespace
   - +whitespace/braces
   - -build/include_what_you_use
   - -runtime/references
   - -readability/casting
   - -build/c++11
   - -runtime/printf
   - -runtime/threadsafe_fn
   style: google