platform: linux | osx

build:
- mkdir build
- cd build
- cmake .. -DBUILD_CURL_TESTS=OFF -DBUILD_CURL_EXE=OFF -DJSONCPP_WITH_TESTS=OFF -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF -DHTTP_ONLY=ON -DUSE_GLOG=OFF
- make
analyzers:
 - cpplint: true
   include: ["*.cpp", "*.h", "*.hpp", "*.c"]
   path: 
   - ./src/base
   - ./src/ali_search
   filters:
   - -whitespace
   - +whitespace/braces
   style: google # webkit | google