language: cpp

compiler:
  - gcc
  - clang

before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - sudo apt-get update

install: 
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir build
  - cd build
  - cmake .. -DBUILD_CURL_TESTS=OFF -DBUILD_CURL_EXE=OFF -DJSONCPP_WITH_TESTS=OFF -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF -DWITH_GFLAGS=OFF -DHTTP_ONLY=ON

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.8
    - g++-4.8
    - clang

script:
 - $CXX --version 
 - make

os:
  - linux
  - osx