#include "ali_search/ali_search.h"
#include "base/basedefines.h"
#include "easylogging++.h"

INITIALIZE_EASYLOGGINGPP

#define GKD(NAME)\
  aos::GET_KLABEL_DESCRIBE(NAME);
#define GKV(NAME)\
  aos::GET_KLABEL_VALUE(NAME)

int main(int argv, char* argc[]){
  
  //
  LOG(INFO) << GKV(INTERNAL_SERVER_ERROR);
  LOG(INFO) << GKD(INTERNAL_SERVER_ERROR);
  LOG(INFO) << aos::INTERNAL_SERVER_ERROR;
  //
  LOG(INFO) << GKV(TEMPLETE_NOT_FOUND);
  LOG(INFO) << GKD(TEMPLETE_NOT_FOUND);
  LOG(INFO) << aos::TEMPLETE_NOT_FOUND;
  //
  LOG(INFO) << GKV(INDEX_TYPE_NOT_SUPPRT);
  LOG(INFO) << GKD(INDEX_TYPE_NOT_SUPPRT);
  LOG(INFO) << aos::INDEX_TYPE_NOT_SUPPRT;
  //
  LOG(INFO) << GKV(SERVICE_UNAVALIABLE);
  LOG(INFO) << GKD(SERVICE_UNAVALIABLE);
  LOG(INFO) << aos::SERVICE_UNAVALIABLE;
  return 0;
}